parameters:
#    mabsi2cf.example.class: mab\si2cfBundle\Example

services:
    kernel.listener.mab_si2cf_exception_listener:
        class: mab\si2cfBundle\Listener\ExceptionListener
        arguments: [@templating, @kernel]
        tags:
        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }